line-length: false
link-fragments: false
single-title: false
no-inline-html:
  allowed_elements:
    - badge
    - eslint-code-block
    - sup
    - rules-table
    - span
descriptive-link-text:
  prohibited_texts:
    - click here
    # - here
    - link
    - more
table-column-style: false  

# enforce consistency
code-block-style:
  style: fenced
code-fence-style:
  style: backtick
emphasis-style:
  style: underscore
heading-style:
  style: atx
hr-style:
  style: ---
strong-style:
  style: asterisk
ul-style:
  style: dash
