/*
 * IMPORTANT!
 * This file has been automatically generated,
 * in order to update it's content execute "npm run update"
 */
module.exports = {
  "vue/html-end-tags": "off",
  "vue/html-no-self-closing": "off",
  "vue/html-quotes": "off",
  "vue/jsx-uses-vars": "error",
  "vue/name-property-casing": "off",
  "vue/no-async-in-computed-properties": "off",
  "vue/no-confusing-v-for-v-if": "error",
  "vue/no-duplicate-attributes": "off",
  "vue/no-invalid-template-root": "error",
  "vue/no-invalid-v-bind": "error",
  "vue/no-invalid-v-cloak": "error",
  "vue/no-invalid-v-else-if": "error",
  "vue/no-invalid-v-else": "error",
  "vue/no-invalid-v-for": "error",
  "vue/no-invalid-v-html": "error",
  "vue/no-invalid-v-if": "error",
  "vue/no-invalid-v-model": "error",
  "vue/no-invalid-v-on": "error",
  "vue/no-invalid-v-once": "error",
  "vue/no-invalid-v-pre": "error",
  "vue/no-invalid-v-show": "error",
  "vue/no-invalid-v-text": "error",
  "vue/no-parsing-error": "error",
  "vue/no-shared-component-data": "off",
  "vue/no-side-effects-in-computed-properties": "off",
  "vue/no-template-key": "off",
  "vue/no-textarea-mustache": "error",
  "vue/order-in-components": "off",
  "vue/require-component-is": "error",
  "vue/require-v-for-key": "error",
  "vue/return-in-computed-property": "off",
  "vue/v-bind-style": "off",
  "vue/v-on-style": "off"
}