name: Check for utils resources update
on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday, see https://crontab.guru/#0_0_*_*_0

permissions:
  contents: write
  pull-requests: write

jobs:
  check-for-resources-update:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'vuejs/eslint-plugin-vue' }}
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Install Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: lts/*
      - name: Install Packages
        run: npm install
      - name: Update
        run: npm run update-resources
      - uses: peter-evans/create-pull-request@22a9089034f40e5a961c8808d113e2c98fb63676 # v7.0.11
        with:
          commit-message: Updates resources
          branch: update-resources
          branch-suffix: timestamp
          title: Updates resources
